# Generated by Django 3.2.5 on 2021-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("application_link", models.URLField()),
                ("salary_range_min", models.IntegerField()),
                ("salary_range_max", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
